### ISSUE TITLE
Fasta folder to Excel file formatting?

### ISSUE THREAD

**Issue by gwendolin** [kbaseapps/MetagenomeUtils#50]
Hi,

I would like to import a folder of FASTA files to my KBase narrative as a binned contigs object, and it seems like I must convert them to an excel file. I am wondering how I should convert/format them as an excel file? Any help would be greatly appreciated.

**Comment by bio-boris** [comment]
hi @gwendolin Can you please open up a ticket at https://www.kbase.us/support/

**Comment by gwendolin** [comment]
@bio-boris will do, thank you!
